id: A4AFF4E8A
base_file: f1636.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:33:56.115091
  last_modified_at: 2022-06-11 13:33:56.115099
